import { Google_Sans } from "next/font/google";
import "./globals.css";

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Readme",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  interactiveWidget: "overlays-content",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={googleSans.variable}
    >
      <body className={`${googleSans.className} antialiased`}>
        <div id="app-scroll">
          {children}
        </div>
      </body>
    </html>
  );
}
